spring:
  application:
    name: BackendBengkel
  config:
    import: optional:env[.env]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  graphql:
    schema:
      locations:
        -none
        #- clas
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: true
    mongodb:
      uri: ${MONGO_DB}
      database: ${DB_MONGO}
  mail:
    host: ${MAIL_HOST_DATA:smtp.gmail.com}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  JWT_SECRET: ${JWT_SECRET}
  JWT_ACTIVATION: ${JWT_ACTIVATION}
  JWT_UPDATE_PROFILE: ${JWT_UPDATE_PROFILE}
  issuer: VehicleBucket

server:
  port: ${PORT_APP}
app:
  baseUrl: ${BASE_URL}

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.beans.factory.support: DEBUG

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
